// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJwYz1JgatkAzJ-5Ud4d0Vo5wed98v7JE',
    appId: '1:162245416287:android:be710feae061220b6412ea',
    messagingSenderId: '162245416287',
    projectId: 'vpn-app-379416',
    databaseURL: 'https://vpn-app-379416-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'vpn-app-379416.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrbRa3MZ_HaiU7KtT2ak9OmLwhNg6bj1A',
    appId: '1:162245416287:ios:b12673fd3906c1656412ea',
    messagingSenderId: '162245416287',
    projectId: 'vpn-app-379416',
    databaseURL: 'https://vpn-app-379416-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'vpn-app-379416.appspot.com',
    iosClientId: '162245416287-5mu94fpmmbhd45m2hg7cfhd7c0qkdtl3.apps.googleusercontent.com',
    iosBundleId: 'com.example.coolVpn',
  );
}
